### ISSUE TITLE
Casper 3.0 support

### ISSUE THREAD

**Issue by onny** [christophery/geist#9]
Hey,
are you also going to support Casper 3.0?

Best regards,
Jonas

**Comment by christophery** [comment]
No current plans to port Casper 3.0 but may reconsider in the future.

**Comment by ghost** [comment]
Would be great 👍🏻

**Comment by christophery** [comment]
Hey all,

👉 [If anyone is interest, I've released a port of Casper 5.0 for WordPress on GitHub.](https://github.com/christophery/proton)

This isn't exactly Casper 3.0 but is very similar in style. I'm going to close this issue because at this point I'm not going back to port an older version of Casper.

Cheers.

**Comment by ghost** [comment]
Nice!!!
